require('plugins')
require('keymaps')
require('settings')
require('config-lsp')
require('config-treesitter')
require('config-telescope')
-- require('config-coq')
require('config-lspkind')
require('config-cmp')
require('config-bufferline')
require('config-nvimtree')
require('colorscheme')
