-- vim.g.firenvim_config = {
--     globalSettings = { alt = "all" },
--     localSettings = {
--         [".*"] = {
--             cmdline  = "neovim",
--             content  = "text",
--             priority = 0,
--             selector = "textarea",
--             takeover = "always"
--         }
--     }
-- }
-- vim.cmd([[set guifont=JetBrains_Mono:h18]])
